"""exclude parameter for password  field

Revision ID: 8357f5e130be
Revises: 64bb1d871181
Create Date: 2025-04-07 13:53:47.230557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # ADD THIS


# revision identifiers, used by Alembic.
revision: str = '8357f5e130be'
down_revision: Union[str, None] = '64bb1d871181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_accounts', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_accounts', type_='unique')
    # ### end Alembic commands ###
